services:
  frontend:
    image: ghcr.io/emilstorgaard/elines-krudtugler-frontend:latest
    container_name: elines-krudtugler-frontend
    restart: unless-stopped
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
